enable_selector = true
selector = "rofi -dmenu -i -p 'Open With: '"
term_exec_args = ''
expand_wildcards = true

[[handlers]]
exec = "mpv --profile=image %U" # Uses desktop entry field codes
terminal = false # Set to true for terminal apps, false for GUI apps (optional; defaults to false)
regexes = ['https?:\/\/[^\s\/$.?#].[^\s]*\.(?:png|jpe?g|gif|svg|webp|bmp|tiff|svg)$'] # Use single-quote literal strings

#[[handlers]]
#exec = "mpv --x11-name='mpv-float' %u"
#terminal = false
#regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.*#__preview']

[[handlers]]
exec = "handlr launch .mkv %u"
terminal = false
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.']
